version: 2
updates:
  - package-ecosystem: gradle
    directory: /kmp-app
    schedule:
      interval: weekly
    groups:
      kotlin-platform:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.compose*"
      android-platform:
        patterns:
          - "com.android*"
          - "androidx*"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
